// Code generated by goctl. DO NOT EDIT.
// Source: plusins_user_rpc.proto

package server

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/plusins_user_rpc/internal/logic/base"
	"github.com/fayipon/gg-pr-plusins/plusins_user_rpc/internal/svc"
	"github.com/fayipon/gg-pr-plusins/plusins_user_rpc/types/plusinsuserrpc"
)

type PlusinsUserRpcServer struct {
	svcCtx *svc.ServiceContext
	plusinsuserrpc.UnimplementedPlusinsUserRpcServer
}

func NewPlusinsUserRpcServer(svcCtx *svc.ServiceContext) *PlusinsUserRpcServer {
	return &PlusinsUserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *PlusinsUserRpcServer) InitDatabase(ctx context.Context, in *plusinsuserrpc.Empty) (*plusinsuserrpc.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
