// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: users.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Users_GetUserList_FullMethodName           = "/users.Users/GetUserList"
	Users_GetUser_FullMethodName               = "/users.Users/GetUser"
	Users_CreateUser_FullMethodName            = "/users.Users/CreateUser"
	Users_CreateUserLevel_FullMethodName       = "/users.Users/CreateUserLevel"
	Users_GetUserLevel_FullMethodName          = "/users.Users/GetUserLevel"
	Users_UpdateUserLevel_FullMethodName       = "/users.Users/UpdateUserLevel"
	Users_DeleteUserLevel_FullMethodName       = "/users.Users/DeleteUserLevel"
	Users_GetUserLevelList_FullMethodName      = "/users.Users/GetUserLevelList"
	Users_GetLevelsBatch_FullMethodName        = "/users.Users/GetLevelsBatch"
	Users_CreateUserGroup_FullMethodName       = "/users.Users/CreateUserGroup"
	Users_GetUserGroup_FullMethodName          = "/users.Users/GetUserGroup"
	Users_UpdateUserGroup_FullMethodName       = "/users.Users/UpdateUserGroup"
	Users_DeleteUserGroup_FullMethodName       = "/users.Users/DeleteUserGroup"
	Users_GetUserGroupList_FullMethodName      = "/users.Users/GetUserGroupList"
	Users_CreateUserTag_FullMethodName         = "/users.Users/CreateUserTag"
	Users_GetUserTag_FullMethodName            = "/users.Users/GetUserTag"
	Users_UpdateUserTag_FullMethodName         = "/users.Users/UpdateUserTag"
	Users_DeleteUserTag_FullMethodName         = "/users.Users/DeleteUserTag"
	Users_GetUserTagList_FullMethodName        = "/users.Users/GetUserTagList"
	Users_CreateUserReferer_FullMethodName     = "/users.Users/CreateUserReferer"
	Users_GetUserReferer_FullMethodName        = "/users.Users/GetUserReferer"
	Users_UpdateUserReferer_FullMethodName     = "/users.Users/UpdateUserReferer"
	Users_DeleteUserReferer_FullMethodName     = "/users.Users/DeleteUserReferer"
	Users_GetUserRefererList_FullMethodName    = "/users.Users/GetUserRefererList"
	Users_GenerateRefererLink_FullMethodName   = "/users.Users/GenerateRefererLink"
	Users_RegisterByRefererLink_FullMethodName = "/users.Users/RegisterByRefererLink"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================
// Service
// =============================
type UsersClient interface {
	GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	// UserLevel
	CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error)
	GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error)
	UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error)
	DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error)
	GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error)
	GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error)
	// UserGroup
	CreateUserGroup(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error)
	GetUserGroup(ctx context.Context, in *GetUserGroupReq, opts ...grpc.CallOption) (*GetUserGroupResp, error)
	UpdateUserGroup(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error)
	DeleteUserGroup(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error)
	GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error)
	// UserTag
	CreateUserTag(ctx context.Context, in *CreateUserTagReq, opts ...grpc.CallOption) (*CreateUserTagResp, error)
	GetUserTag(ctx context.Context, in *GetUserTagReq, opts ...grpc.CallOption) (*GetUserTagResp, error)
	UpdateUserTag(ctx context.Context, in *UpdateUserTagReq, opts ...grpc.CallOption) (*UpdateUserTagResp, error)
	DeleteUserTag(ctx context.Context, in *DeleteUserTagReq, opts ...grpc.CallOption) (*DeleteUserTagResp, error)
	GetUserTagList(ctx context.Context, in *GetUserTagListReq, opts ...grpc.CallOption) (*GetUserTagListResp, error)
	// UserReferer
	CreateUserReferer(ctx context.Context, in *CreateUserRefererReq, opts ...grpc.CallOption) (*CreateUserRefererResp, error)
	GetUserReferer(ctx context.Context, in *GetUserRefererReq, opts ...grpc.CallOption) (*GetUserRefererResp, error)
	UpdateUserReferer(ctx context.Context, in *UpdateUserRefererReq, opts ...grpc.CallOption) (*UpdateUserRefererResp, error)
	DeleteUserReferer(ctx context.Context, in *DeleteUserRefererReq, opts ...grpc.CallOption) (*DeleteUserRefererResp, error)
	GetUserRefererList(ctx context.Context, in *GetUserRefererListReq, opts ...grpc.CallOption) (*GetUserRefererListResp, error)
	GenerateRefererLink(ctx context.Context, in *GenerateRefererLinkReq, opts ...grpc.CallOption) (*GenerateRefererLinkResp, error)
	RegisterByRefererLink(ctx context.Context, in *RegisterByRefererLinkReq, opts ...grpc.CallOption) (*RegisterByRefererLinkResp, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListResp)
	err := c.cc.Invoke(ctx, Users_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, Users_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, Users_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserLevelResp)
	err := c.cc.Invoke(ctx, Users_CreateUserLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLevelResp)
	err := c.cc.Invoke(ctx, Users_GetUserLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserLevelResp)
	err := c.cc.Invoke(ctx, Users_UpdateUserLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserLevelResp)
	err := c.cc.Invoke(ctx, Users_DeleteUserLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLevelListResp)
	err := c.cc.Invoke(ctx, Users_GetUserLevelList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LevelBatchResp)
	err := c.cc.Invoke(ctx, Users_GetLevelsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUserGroup(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserGroupResp)
	err := c.cc.Invoke(ctx, Users_CreateUserGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserGroup(ctx context.Context, in *GetUserGroupReq, opts ...grpc.CallOption) (*GetUserGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupResp)
	err := c.cc.Invoke(ctx, Users_GetUserGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUserGroup(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserGroupResp)
	err := c.cc.Invoke(ctx, Users_UpdateUserGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserGroup(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserGroupResp)
	err := c.cc.Invoke(ctx, Users_DeleteUserGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupListResp)
	err := c.cc.Invoke(ctx, Users_GetUserGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUserTag(ctx context.Context, in *CreateUserTagReq, opts ...grpc.CallOption) (*CreateUserTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserTagResp)
	err := c.cc.Invoke(ctx, Users_CreateUserTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserTag(ctx context.Context, in *GetUserTagReq, opts ...grpc.CallOption) (*GetUserTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTagResp)
	err := c.cc.Invoke(ctx, Users_GetUserTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUserTag(ctx context.Context, in *UpdateUserTagReq, opts ...grpc.CallOption) (*UpdateUserTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserTagResp)
	err := c.cc.Invoke(ctx, Users_UpdateUserTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserTag(ctx context.Context, in *DeleteUserTagReq, opts ...grpc.CallOption) (*DeleteUserTagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserTagResp)
	err := c.cc.Invoke(ctx, Users_DeleteUserTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserTagList(ctx context.Context, in *GetUserTagListReq, opts ...grpc.CallOption) (*GetUserTagListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTagListResp)
	err := c.cc.Invoke(ctx, Users_GetUserTagList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) CreateUserReferer(ctx context.Context, in *CreateUserRefererReq, opts ...grpc.CallOption) (*CreateUserRefererResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserRefererResp)
	err := c.cc.Invoke(ctx, Users_CreateUserReferer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserReferer(ctx context.Context, in *GetUserRefererReq, opts ...grpc.CallOption) (*GetUserRefererResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRefererResp)
	err := c.cc.Invoke(ctx, Users_GetUserReferer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateUserReferer(ctx context.Context, in *UpdateUserRefererReq, opts ...grpc.CallOption) (*UpdateUserRefererResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRefererResp)
	err := c.cc.Invoke(ctx, Users_UpdateUserReferer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteUserReferer(ctx context.Context, in *DeleteUserRefererReq, opts ...grpc.CallOption) (*DeleteUserRefererResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserRefererResp)
	err := c.cc.Invoke(ctx, Users_DeleteUserReferer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUserRefererList(ctx context.Context, in *GetUserRefererListReq, opts ...grpc.CallOption) (*GetUserRefererListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRefererListResp)
	err := c.cc.Invoke(ctx, Users_GetUserRefererList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GenerateRefererLink(ctx context.Context, in *GenerateRefererLinkReq, opts ...grpc.CallOption) (*GenerateRefererLinkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRefererLinkResp)
	err := c.cc.Invoke(ctx, Users_GenerateRefererLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) RegisterByRefererLink(ctx context.Context, in *RegisterByRefererLinkReq, opts ...grpc.CallOption) (*RegisterByRefererLinkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterByRefererLinkResp)
	err := c.cc.Invoke(ctx, Users_RegisterByRefererLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility.
//
// =============================
// Service
// =============================
type UsersServer interface {
	GetUserList(context.Context, *GetUserListReq) (*GetUserListResp, error)
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	// UserLevel
	CreateUserLevel(context.Context, *CreateUserLevelReq) (*CreateUserLevelResp, error)
	GetUserLevel(context.Context, *GetUserLevelReq) (*GetUserLevelResp, error)
	UpdateUserLevel(context.Context, *UpdateUserLevelReq) (*UpdateUserLevelResp, error)
	DeleteUserLevel(context.Context, *DeleteUserLevelReq) (*DeleteUserLevelResp, error)
	GetUserLevelList(context.Context, *GetUserLevelListReq) (*GetUserLevelListResp, error)
	GetLevelsBatch(context.Context, *LevelBatchReq) (*LevelBatchResp, error)
	// UserGroup
	CreateUserGroup(context.Context, *CreateUserGroupReq) (*CreateUserGroupResp, error)
	GetUserGroup(context.Context, *GetUserGroupReq) (*GetUserGroupResp, error)
	UpdateUserGroup(context.Context, *UpdateUserGroupReq) (*UpdateUserGroupResp, error)
	DeleteUserGroup(context.Context, *DeleteUserGroupReq) (*DeleteUserGroupResp, error)
	GetUserGroupList(context.Context, *GetUserGroupListReq) (*GetUserGroupListResp, error)
	// UserTag
	CreateUserTag(context.Context, *CreateUserTagReq) (*CreateUserTagResp, error)
	GetUserTag(context.Context, *GetUserTagReq) (*GetUserTagResp, error)
	UpdateUserTag(context.Context, *UpdateUserTagReq) (*UpdateUserTagResp, error)
	DeleteUserTag(context.Context, *DeleteUserTagReq) (*DeleteUserTagResp, error)
	GetUserTagList(context.Context, *GetUserTagListReq) (*GetUserTagListResp, error)
	// UserReferer
	CreateUserReferer(context.Context, *CreateUserRefererReq) (*CreateUserRefererResp, error)
	GetUserReferer(context.Context, *GetUserRefererReq) (*GetUserRefererResp, error)
	UpdateUserReferer(context.Context, *UpdateUserRefererReq) (*UpdateUserRefererResp, error)
	DeleteUserReferer(context.Context, *DeleteUserRefererReq) (*DeleteUserRefererResp, error)
	GetUserRefererList(context.Context, *GetUserRefererListReq) (*GetUserRefererListResp, error)
	GenerateRefererLink(context.Context, *GenerateRefererLinkReq) (*GenerateRefererLinkResp, error)
	RegisterByRefererLink(context.Context, *RegisterByRefererLinkReq) (*RegisterByRefererLinkResp, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServer struct{}

func (UnimplementedUsersServer) GetUserList(context.Context, *GetUserListReq) (*GetUserListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedUsersServer) GetUser(context.Context, *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsersServer) CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUsersServer) CreateUserLevel(context.Context, *CreateUserLevelReq) (*CreateUserLevelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserLevel not implemented")
}
func (UnimplementedUsersServer) GetUserLevel(context.Context, *GetUserLevelReq) (*GetUserLevelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLevel not implemented")
}
func (UnimplementedUsersServer) UpdateUserLevel(context.Context, *UpdateUserLevelReq) (*UpdateUserLevelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserLevel not implemented")
}
func (UnimplementedUsersServer) DeleteUserLevel(context.Context, *DeleteUserLevelReq) (*DeleteUserLevelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserLevel not implemented")
}
func (UnimplementedUsersServer) GetUserLevelList(context.Context, *GetUserLevelListReq) (*GetUserLevelListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLevelList not implemented")
}
func (UnimplementedUsersServer) GetLevelsBatch(context.Context, *LevelBatchReq) (*LevelBatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLevelsBatch not implemented")
}
func (UnimplementedUsersServer) CreateUserGroup(context.Context, *CreateUserGroupReq) (*CreateUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserGroup not implemented")
}
func (UnimplementedUsersServer) GetUserGroup(context.Context, *GetUserGroupReq) (*GetUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroup not implemented")
}
func (UnimplementedUsersServer) UpdateUserGroup(context.Context, *UpdateUserGroupReq) (*UpdateUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserGroup not implemented")
}
func (UnimplementedUsersServer) DeleteUserGroup(context.Context, *DeleteUserGroupReq) (*DeleteUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserGroup not implemented")
}
func (UnimplementedUsersServer) GetUserGroupList(context.Context, *GetUserGroupListReq) (*GetUserGroupListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGroupList not implemented")
}
func (UnimplementedUsersServer) CreateUserTag(context.Context, *CreateUserTagReq) (*CreateUserTagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserTag not implemented")
}
func (UnimplementedUsersServer) GetUserTag(context.Context, *GetUserTagReq) (*GetUserTagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTag not implemented")
}
func (UnimplementedUsersServer) UpdateUserTag(context.Context, *UpdateUserTagReq) (*UpdateUserTagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserTag not implemented")
}
func (UnimplementedUsersServer) DeleteUserTag(context.Context, *DeleteUserTagReq) (*DeleteUserTagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserTag not implemented")
}
func (UnimplementedUsersServer) GetUserTagList(context.Context, *GetUserTagListReq) (*GetUserTagListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTagList not implemented")
}
func (UnimplementedUsersServer) CreateUserReferer(context.Context, *CreateUserRefererReq) (*CreateUserRefererResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserReferer not implemented")
}
func (UnimplementedUsersServer) GetUserReferer(context.Context, *GetUserRefererReq) (*GetUserRefererResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReferer not implemented")
}
func (UnimplementedUsersServer) UpdateUserReferer(context.Context, *UpdateUserRefererReq) (*UpdateUserRefererResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserReferer not implemented")
}
func (UnimplementedUsersServer) DeleteUserReferer(context.Context, *DeleteUserRefererReq) (*DeleteUserRefererResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserReferer not implemented")
}
func (UnimplementedUsersServer) GetUserRefererList(context.Context, *GetUserRefererListReq) (*GetUserRefererListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRefererList not implemented")
}
func (UnimplementedUsersServer) GenerateRefererLink(context.Context, *GenerateRefererLinkReq) (*GenerateRefererLinkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRefererLink not implemented")
}
func (UnimplementedUsersServer) RegisterByRefererLink(context.Context, *RegisterByRefererLinkReq) (*RegisterByRefererLinkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterByRefererLink not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}
func (UnimplementedUsersServer) testEmbeddedByValue()               {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	// If the following call pancis, it indicates UnimplementedUsersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserList(ctx, req.(*GetUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUserLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUserLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_CreateUserLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUserLevel(ctx, req.(*CreateUserLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserLevel(ctx, req.(*GetUserLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUserLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUserLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpdateUserLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUserLevel(ctx, req.(*UpdateUserLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteUserLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserLevel(ctx, req.(*DeleteUserLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserLevelList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLevelListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserLevelList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserLevelList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserLevelList(ctx, req.(*GetUserLevelListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetLevelsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LevelBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetLevelsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetLevelsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetLevelsBatch(ctx, req.(*LevelBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_CreateUserGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUserGroup(ctx, req.(*CreateUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserGroup(ctx, req.(*GetUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpdateUserGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUserGroup(ctx, req.(*UpdateUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteUserGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserGroup(ctx, req.(*DeleteUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserGroupList(ctx, req.(*GetUserGroupListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUserTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUserTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_CreateUserTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUserTag(ctx, req.(*CreateUserTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserTag(ctx, req.(*GetUserTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUserTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUserTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpdateUserTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUserTag(ctx, req.(*UpdateUserTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteUserTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserTag(ctx, req.(*DeleteUserTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserTagList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTagListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserTagList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserTagList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserTagList(ctx, req.(*GetUserTagListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_CreateUserReferer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRefererReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateUserReferer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_CreateUserReferer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateUserReferer(ctx, req.(*CreateUserRefererReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserReferer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRefererReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserReferer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserReferer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserReferer(ctx, req.(*GetUserRefererReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateUserReferer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRefererReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUserReferer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_UpdateUserReferer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUserReferer(ctx, req.(*UpdateUserRefererReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteUserReferer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRefererReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteUserReferer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteUserReferer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteUserReferer(ctx, req.(*DeleteUserRefererReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUserRefererList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRefererListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUserRefererList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUserRefererList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUserRefererList(ctx, req.(*GetUserRefererListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GenerateRefererLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRefererLinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GenerateRefererLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GenerateRefererLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GenerateRefererLink(ctx, req.(*GenerateRefererLinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_RegisterByRefererLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterByRefererLinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).RegisterByRefererLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_RegisterByRefererLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).RegisterByRefererLink(ctx, req.(*RegisterByRefererLinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserList",
			Handler:    _Users_GetUserList_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Users_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Users_CreateUser_Handler,
		},
		{
			MethodName: "CreateUserLevel",
			Handler:    _Users_CreateUserLevel_Handler,
		},
		{
			MethodName: "GetUserLevel",
			Handler:    _Users_GetUserLevel_Handler,
		},
		{
			MethodName: "UpdateUserLevel",
			Handler:    _Users_UpdateUserLevel_Handler,
		},
		{
			MethodName: "DeleteUserLevel",
			Handler:    _Users_DeleteUserLevel_Handler,
		},
		{
			MethodName: "GetUserLevelList",
			Handler:    _Users_GetUserLevelList_Handler,
		},
		{
			MethodName: "GetLevelsBatch",
			Handler:    _Users_GetLevelsBatch_Handler,
		},
		{
			MethodName: "CreateUserGroup",
			Handler:    _Users_CreateUserGroup_Handler,
		},
		{
			MethodName: "GetUserGroup",
			Handler:    _Users_GetUserGroup_Handler,
		},
		{
			MethodName: "UpdateUserGroup",
			Handler:    _Users_UpdateUserGroup_Handler,
		},
		{
			MethodName: "DeleteUserGroup",
			Handler:    _Users_DeleteUserGroup_Handler,
		},
		{
			MethodName: "GetUserGroupList",
			Handler:    _Users_GetUserGroupList_Handler,
		},
		{
			MethodName: "CreateUserTag",
			Handler:    _Users_CreateUserTag_Handler,
		},
		{
			MethodName: "GetUserTag",
			Handler:    _Users_GetUserTag_Handler,
		},
		{
			MethodName: "UpdateUserTag",
			Handler:    _Users_UpdateUserTag_Handler,
		},
		{
			MethodName: "DeleteUserTag",
			Handler:    _Users_DeleteUserTag_Handler,
		},
		{
			MethodName: "GetUserTagList",
			Handler:    _Users_GetUserTagList_Handler,
		},
		{
			MethodName: "CreateUserReferer",
			Handler:    _Users_CreateUserReferer_Handler,
		},
		{
			MethodName: "GetUserReferer",
			Handler:    _Users_GetUserReferer_Handler,
		},
		{
			MethodName: "UpdateUserReferer",
			Handler:    _Users_UpdateUserReferer_Handler,
		},
		{
			MethodName: "DeleteUserReferer",
			Handler:    _Users_DeleteUserReferer_Handler,
		},
		{
			MethodName: "GetUserRefererList",
			Handler:    _Users_GetUserRefererList_Handler,
		},
		{
			MethodName: "GenerateRefererLink",
			Handler:    _Users_GenerateRefererLink_Handler,
		},
		{
			MethodName: "RegisterByRefererLink",
			Handler:    _Users_RegisterByRefererLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
