// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: users.proto

package usersclient

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/users_rpc/users/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserGroupReq   = users.CreateUserGroupReq
	CreateUserGroupResp  = users.CreateUserGroupResp
	CreateUserLevelReq   = users.CreateUserLevelReq
	CreateUserLevelResp  = users.CreateUserLevelResp
	CreateUserReq        = users.CreateUserReq
	CreateUserResp       = users.CreateUserResp
	CreateUserTagReq     = users.CreateUserTagReq
	CreateUserTagResp    = users.CreateUserTagResp
	DeleteUserGroupReq   = users.DeleteUserGroupReq
	DeleteUserGroupResp  = users.DeleteUserGroupResp
	DeleteUserLevelReq   = users.DeleteUserLevelReq
	DeleteUserLevelResp  = users.DeleteUserLevelResp
	DeleteUserTagReq     = users.DeleteUserTagReq
	DeleteUserTagResp    = users.DeleteUserTagResp
	GetUserGroupListReq  = users.GetUserGroupListReq
	GetUserGroupListResp = users.GetUserGroupListResp
	GetUserGroupReq      = users.GetUserGroupReq
	GetUserGroupResp     = users.GetUserGroupResp
	GetUserLevelListReq  = users.GetUserLevelListReq
	GetUserLevelListResp = users.GetUserLevelListResp
	GetUserLevelReq      = users.GetUserLevelReq
	GetUserLevelResp     = users.GetUserLevelResp
	GetUserListReq       = users.GetUserListReq
	GetUserListResp      = users.GetUserListResp
	GetUserReq           = users.GetUserReq
	GetUserResp          = users.GetUserResp
	GetUserTagListReq    = users.GetUserTagListReq
	GetUserTagListResp   = users.GetUserTagListResp
	GetUserTagReq        = users.GetUserTagReq
	GetUserTagResp       = users.GetUserTagResp
	LevelBatchReq        = users.LevelBatchReq
	LevelBatchResp       = users.LevelBatchResp
	UpdateUserGroupReq   = users.UpdateUserGroupReq
	UpdateUserGroupResp  = users.UpdateUserGroupResp
	UpdateUserLevelReq   = users.UpdateUserLevelReq
	UpdateUserLevelResp  = users.UpdateUserLevelResp
	UpdateUserTagReq     = users.UpdateUserTagReq
	UpdateUserTagResp    = users.UpdateUserTagResp
	UserGroupInfo        = users.UserGroupInfo
	UserItem             = users.UserItem
	UserLevelInfo        = users.UserLevelInfo
	UserTagInfo          = users.UserTagInfo

	Users interface {
		GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		// UserLevel
		CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error)
		GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error)
		UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error)
		DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error)
		GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error)
		GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error)
		// UserGroup
		CreateUserGroup(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error)
		GetUserGroup(ctx context.Context, in *GetUserGroupReq, opts ...grpc.CallOption) (*GetUserGroupResp, error)
		UpdateUserGroup(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error)
		DeleteUserGroup(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error)
		GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error)
		// UserTag
		CreateUserTag(ctx context.Context, in *CreateUserTagReq, opts ...grpc.CallOption) (*CreateUserTagResp, error)
		GetUserTag(ctx context.Context, in *GetUserTagReq, opts ...grpc.CallOption) (*GetUserTagResp, error)
		UpdateUserTag(ctx context.Context, in *UpdateUserTagReq, opts ...grpc.CallOption) (*UpdateUserTagResp, error)
		DeleteUserTag(ctx context.Context, in *DeleteUserTagReq, opts ...grpc.CallOption) (*DeleteUserTagResp, error)
		GetUserTagList(ctx context.Context, in *GetUserTagListReq, opts ...grpc.CallOption) (*GetUserTagListResp, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultUsers) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUsers) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

// UserLevel
func (m *defaultUsers) CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.UpdateUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.DeleteUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserLevelList(ctx, in, opts...)
}

func (m *defaultUsers) GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetLevelsBatch(ctx, in, opts...)
}

// UserGroup
func (m *defaultUsers) CreateUserGroup(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUserGroup(ctx, in, opts...)
}

func (m *defaultUsers) GetUserGroup(ctx context.Context, in *GetUserGroupReq, opts ...grpc.CallOption) (*GetUserGroupResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserGroup(ctx, in, opts...)
}

func (m *defaultUsers) UpdateUserGroup(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.UpdateUserGroup(ctx, in, opts...)
}

func (m *defaultUsers) DeleteUserGroup(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.DeleteUserGroup(ctx, in, opts...)
}

func (m *defaultUsers) GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserGroupList(ctx, in, opts...)
}

// UserTag
func (m *defaultUsers) CreateUserTag(ctx context.Context, in *CreateUserTagReq, opts ...grpc.CallOption) (*CreateUserTagResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUserTag(ctx, in, opts...)
}

func (m *defaultUsers) GetUserTag(ctx context.Context, in *GetUserTagReq, opts ...grpc.CallOption) (*GetUserTagResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserTag(ctx, in, opts...)
}

func (m *defaultUsers) UpdateUserTag(ctx context.Context, in *UpdateUserTagReq, opts ...grpc.CallOption) (*UpdateUserTagResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.UpdateUserTag(ctx, in, opts...)
}

func (m *defaultUsers) DeleteUserTag(ctx context.Context, in *DeleteUserTagReq, opts ...grpc.CallOption) (*DeleteUserTagResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.DeleteUserTag(ctx, in, opts...)
}

func (m *defaultUsers) GetUserTagList(ctx context.Context, in *GetUserTagListReq, opts ...grpc.CallOption) (*GetUserTagListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserTagList(ctx, in, opts...)
}
