// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: users.proto

package usersclient

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/users_rpc/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserReq   = users.CreateUserReq
	CreateUserResp  = users.CreateUserResp
	GetUserListReq  = users.GetUserListReq
	GetUserListResp = users.GetUserListResp
	GetUserReq      = users.GetUserReq
	GetUserResp     = users.GetUserResp
	LevelBatchReq   = users.LevelBatchReq
	LevelBatchResp  = users.LevelBatchResp
	UserItem        = users.UserItem
	UserLevelInfo   = users.UserLevelInfo

	Users interface {
		GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultUsers) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUsers) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUsers) GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetLevelsBatch(ctx, in, opts...)
}
