// Code generated by goctl. DO NOT EDIT.
// goctls v1.12.1

package handler

import (
	"net/http"

	base "github.com/fayipon/gg-pr-plusins/example/internal/handler/base"
	"github.com/fayipon/gg-pr-plusins/example/internal/svc"

	"github.com/zeromicro/go-zero/rest"

	"github.com/fayipon/gg-pr-plusins/example/internal/handler/sysapi"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)

	server.AddRoute(rest.Route{
		Method:  http.MethodGet,
		Path:    "/sys-api/version",
		Handler: sysapi.VersionHandler(serverCtx),
	})
}
