// Code generated by goctl. DO NOT EDIT.
// Source: plusins_user_rpc.proto

package plusinsuserrpcclient

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/plusins_user_rpc/types/plusinsuserrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = plusinsuserrpc.BaseIDInt32Resp
	BaseIDInt64Resp  = plusinsuserrpc.BaseIDInt64Resp
	BaseIDResp       = plusinsuserrpc.BaseIDResp
	BaseIDStringResp = plusinsuserrpc.BaseIDStringResp
	BaseIDUint32Resp = plusinsuserrpc.BaseIDUint32Resp
	BaseResp         = plusinsuserrpc.BaseResp
	BaseUUIDResp     = plusinsuserrpc.BaseUUIDResp
	Empty            = plusinsuserrpc.Empty
	IDInt32Req       = plusinsuserrpc.IDInt32Req
	IDInt64Req       = plusinsuserrpc.IDInt64Req
	IDReq            = plusinsuserrpc.IDReq
	IDStringReq      = plusinsuserrpc.IDStringReq
	IDUint32Req      = plusinsuserrpc.IDUint32Req
	IDsInt32Req      = plusinsuserrpc.IDsInt32Req
	IDsInt64Req      = plusinsuserrpc.IDsInt64Req
	IDsReq           = plusinsuserrpc.IDsReq
	IDsStringReq     = plusinsuserrpc.IDsStringReq
	IDsUint32Req     = plusinsuserrpc.IDsUint32Req
	PageInfoReq      = plusinsuserrpc.PageInfoReq
	UUIDReq          = plusinsuserrpc.UUIDReq
	UUIDsReq         = plusinsuserrpc.UUIDsReq

	PlusinsUserRpc interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultPlusinsUserRpc struct {
		cli zrpc.Client
	}
)

func NewPlusinsUserRpc(cli zrpc.Client) PlusinsUserRpc {
	return &defaultPlusinsUserRpc{
		cli: cli,
	}
}

func (m *defaultPlusinsUserRpc) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := plusinsuserrpc.NewPlusinsUserRpcClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
