// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MerchantsColumns holds the columns for the "merchants" table.
	MerchantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "merchant_code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "contact_email", Type: field.TypeString},
		{Name: "contact_phone", Type: field.TypeString, Nullable: true},
		{Name: "domain", Type: field.TypeString, Nullable: true},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// MerchantsTable holds the schema information for the "merchants" table.
	MerchantsTable = &schema.Table{
		Name:       "merchants",
		Columns:    MerchantsColumns,
		PrimaryKey: []*schema.Column{MerchantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MerchantsTable,
	}
)

func init() {
}
