// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: users.proto

package usersclient

import (
	"context"

	"gg-pr-plusins/users_rpc/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserLevelReq   = users.CreateUserLevelReq
	CreateUserLevelResp  = users.CreateUserLevelResp
	CreateUserReq        = users.CreateUserReq
	CreateUserResp       = users.CreateUserResp
	DeleteUserLevelReq   = users.DeleteUserLevelReq
	DeleteUserLevelResp  = users.DeleteUserLevelResp
	GetLevelListReq      = users.GetLevelListReq
	GetLevelListResp     = users.GetLevelListResp
	GetUserLevelListReq  = users.GetUserLevelListReq
	GetUserLevelListResp = users.GetUserLevelListResp
	GetUserLevelReq      = users.GetUserLevelReq
	GetUserLevelResp     = users.GetUserLevelResp
	GetUserListReq       = users.GetUserListReq
	GetUserListResp      = users.GetUserListResp
	GetUserReq           = users.GetUserReq
	GetUserResp          = users.GetUserResp
	LevelBatchReq        = users.LevelBatchReq
	LevelBatchResp       = users.LevelBatchResp
	UpdateUserLevelReq   = users.UpdateUserLevelReq
	UpdateUserLevelResp  = users.UpdateUserLevelResp
	UserItem             = users.UserItem
	UserLevelInfo        = users.UserLevelInfo

	Users interface {
		GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
		CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error)
		GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error)
		UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error)
		DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error)
		GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error)
		GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultUsers) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUsers) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUsers) CreateUserLevel(ctx context.Context, in *CreateUserLevelReq, opts ...grpc.CallOption) (*CreateUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) GetUserLevel(ctx context.Context, in *GetUserLevelReq, opts ...grpc.CallOption) (*GetUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) UpdateUserLevel(ctx context.Context, in *UpdateUserLevelReq, opts ...grpc.CallOption) (*UpdateUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.UpdateUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) DeleteUserLevel(ctx context.Context, in *DeleteUserLevelReq, opts ...grpc.CallOption) (*DeleteUserLevelResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.DeleteUserLevel(ctx, in, opts...)
}

func (m *defaultUsers) GetUserLevelList(ctx context.Context, in *GetUserLevelListReq, opts ...grpc.CallOption) (*GetUserLevelListResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetUserLevelList(ctx, in, opts...)
}

func (m *defaultUsers) GetLevelsBatch(ctx context.Context, in *LevelBatchReq, opts ...grpc.CallOption) (*LevelBatchResp, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.GetLevelsBatch(ctx, in, opts...)
}
