// Code generated by goctl. DO NOT EDIT.
// Source: plusins_rpc.proto

package server

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/plusins_rpc/internal/logic/base"
	"github.com/fayipon/gg-pr-plusins/plusins_rpc/internal/svc"
	"github.com/fayipon/gg-pr-plusins/plusins_rpc/types/plusinsrpc"
)

type PlusinsRpcServer struct {
	svcCtx *svc.ServiceContext
	plusinsrpc.UnimplementedPlusinsRpcServer
}

func NewPlusinsRpcServer(svcCtx *svc.ServiceContext) *PlusinsRpcServer {
	return &PlusinsRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *PlusinsRpcServer) InitDatabase(ctx context.Context, in *plusinsrpc.Empty) (*plusinsrpc.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
