// Code generated by goctl. DO NOT EDIT.
// Source: plusins_rpc.proto

package plusinsrpcclient

import (
	"context"

	"github.com/fayipon/gg-pr-plusins/plusins_rpc/types/plusinsrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = plusinsrpc.BaseIDInt32Resp
	BaseIDInt64Resp  = plusinsrpc.BaseIDInt64Resp
	BaseIDResp       = plusinsrpc.BaseIDResp
	BaseIDStringResp = plusinsrpc.BaseIDStringResp
	BaseIDUint32Resp = plusinsrpc.BaseIDUint32Resp
	BaseResp         = plusinsrpc.BaseResp
	BaseUUIDResp     = plusinsrpc.BaseUUIDResp
	Empty            = plusinsrpc.Empty
	IDInt32Req       = plusinsrpc.IDInt32Req
	IDInt64Req       = plusinsrpc.IDInt64Req
	IDReq            = plusinsrpc.IDReq
	IDStringReq      = plusinsrpc.IDStringReq
	IDUint32Req      = plusinsrpc.IDUint32Req
	IDsInt32Req      = plusinsrpc.IDsInt32Req
	IDsInt64Req      = plusinsrpc.IDsInt64Req
	IDsReq           = plusinsrpc.IDsReq
	IDsStringReq     = plusinsrpc.IDsStringReq
	IDsUint32Req     = plusinsrpc.IDsUint32Req
	PageInfoReq      = plusinsrpc.PageInfoReq
	UUIDReq          = plusinsrpc.UUIDReq
	UUIDsReq         = plusinsrpc.UUIDsReq

	PlusinsRpc interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultPlusinsRpc struct {
		cli zrpc.Client
	}
)

func NewPlusinsRpc(cli zrpc.Client) PlusinsRpc {
	return &defaultPlusinsRpc{
		cli: cli,
	}
}

func (m *defaultPlusinsRpc) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := plusinsrpc.NewPlusinsRpcClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
