// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.2
// source: plusins_user_rpc.proto

package plusinsuserrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlusinsUserRpc_InitDatabase_FullMethodName = "/plusinsuserrpc.PlusinsUserRpc/initDatabase"
)

// PlusinsUserRpcClient is the client API for PlusinsUserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlusinsUserRpcClient interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
}

type plusinsUserRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPlusinsUserRpcClient(cc grpc.ClientConnInterface) PlusinsUserRpcClient {
	return &plusinsUserRpcClient{cc}
}

func (c *plusinsUserRpcClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, PlusinsUserRpc_InitDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlusinsUserRpcServer is the server API for PlusinsUserRpc service.
// All implementations must embed UnimplementedPlusinsUserRpcServer
// for forward compatibility.
type PlusinsUserRpcServer interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	mustEmbedUnimplementedPlusinsUserRpcServer()
}

// UnimplementedPlusinsUserRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlusinsUserRpcServer struct{}

func (UnimplementedPlusinsUserRpcServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedPlusinsUserRpcServer) mustEmbedUnimplementedPlusinsUserRpcServer() {}
func (UnimplementedPlusinsUserRpcServer) testEmbeddedByValue()                        {}

// UnsafePlusinsUserRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlusinsUserRpcServer will
// result in compilation errors.
type UnsafePlusinsUserRpcServer interface {
	mustEmbedUnimplementedPlusinsUserRpcServer()
}

func RegisterPlusinsUserRpcServer(s grpc.ServiceRegistrar, srv PlusinsUserRpcServer) {
	// If the following call pancis, it indicates UnimplementedPlusinsUserRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlusinsUserRpc_ServiceDesc, srv)
}

func _PlusinsUserRpc_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlusinsUserRpcServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlusinsUserRpc_InitDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlusinsUserRpcServer).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PlusinsUserRpc_ServiceDesc is the grpc.ServiceDesc for PlusinsUserRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlusinsUserRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plusinsuserrpc.PlusinsUserRpc",
	HandlerType: (*PlusinsUserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _PlusinsUserRpc_InitDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plusins_user_rpc.proto",
}
