// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/fayipon/gg-pr-plusins/plusins_business/internal/ent/merchant"
	"github.com/fayipon/gg-pr-plusins/plusins_business/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	merchantFields := schema.Merchant{}.Fields()
	_ = merchantFields
	// merchantDescStatus is the schema descriptor for status field.
	merchantDescStatus := merchantFields[6].Descriptor()
	// merchant.DefaultStatus holds the default value on creation for the status field.
	merchant.DefaultStatus = merchantDescStatus.Default.(string)
}
