// Code generated by goctl. DO NOT EDIT.
package types

type RegisterBusinessReq struct {
	Name     string `json:"name"`
	Region   string `json:"region"`
	Currency string `json:"currency"`
	Locale   string `json:"locale"`
}

type RegisterBusinessResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	Region   string `json:"region"`
	Currency string `json:"currency"`
	Locale   string `json:"locale"`
	Status   string `json:"status"`
}

type InstallModuleReq struct {
	ModuleCode string `json:"moduleCode"`
}

type InstallModuleResp struct {
	ModuleCode string `json:"moduleCode"`
	LicenseKey string `json:"licenseKey"`
	Status     string `json:"status"`
}
